version: 0
#verbose: true
run: &default_runner
  mounts: # mount configurations Available keys: NOW, UUID,
    - !mounts.SSHCode &code_mount
      local_path: .
      local_tar: /home/ravan/jaynes/{now:%Y-%m-%d}/{now:%H%M%S.%f}-lucidxr.tar
      host_path: "{secret.JYNS_SLURM_DIR}/lucidxr/{now:%Y-%m-%d}/{now:%H%M%S.%f}-lucidxr"
      remote_tar: "{secret.JYNS_SLURM_DIR}/lucidxr/{now:%Y-%m-%d}/{now:%H%M%S.%f}-lucidxr.tar"
      pypath: true
      # exclude_ignore: .gitignore
      excludes: >-
        --exclude='./docs' --exclude='data' --exclude='dist'
        --exclude='.pytest_cache' --exclude='datasets' --exclude='docs' --exclude='specs'
        --exclude='outputs' --exclude='figures' --exclude='results' --exclude='analysis' 
        --exclude='*.ipynb' --exclude='*__pycache__' --exclude='*.egg-info'
        --exclude='*.git' --exclude='*.gif' --exclude='*.mp4' --exclude='*.idea'
        --exclude='*.pkl' --exclude='*.log*' --exclude='*.hdf5' --exclude="**/eval_envs"
        --exclude='**/orbit' --exclude='.cache'
      compress: true
    - !mounts.SSHCode &code_mount_posterior-sculpting
      local_path: ../posterior-sculpting
      local_tar: /home/ravan/jaynes/{now:%Y-%m-%d}/{now:%H%M%S.%f}-posterior-sculpting.tar
      host_path: "{secret.JYNS_SLURM_DIR}/jaynes_mount/lucidxr/{now:%Y-%m-%d}/{now:%H%M%S.%f}-posterior-sculpting"
      remote_tar: "{secret.JYNS_SLURM_DIR}/jaynes_mount/lucidxr/{now:%Y-%m-%d}/{now:%H%M%S.%f}-posterior-sculpting.tar"
      pypath: true
      excludes: >-
        --exclude='samples' --exclude='images' --exclude='videos' --exclude='datasets'
        --exclude='figures' --exclude='results' --exclude='analysis' --exclude='*.ipynb'
        --exclude='*__pycache__' --exclude='*.git'  --exclude='*.gif'
        --exclude='*.mp4' --exclude='*.idea' --exclude='*.egg-info' --exclude='*.pkl'
        --exclude='*.safetensors'
        --exclude='/models'
        --exclude='*.zip'
        --exclude='*.tar'
        --exclude='*/logs/*'
        --exclude="*.cache"
        --exclude='*.jpg'
        --exclude='*.jpeg'
        --exclude='*.JPG'
        --exclude='*.PNG'
        --exclude='*.png'
        --exclude=web
        --exclude=output
        --exclude=tests
        --exclude=tests-ui
        --exclude='*.md'
      compress: true
  runner: !runners.Slurm &slurm
    envs: >-
      LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8 LANGUAGE=en_US MUJOCO_GL=egl
    startup: >-
      . /data/scratch/{secret.JYNS_USERNAME}/.jaynes_init;
      conda activate torch311;
      export ZAKU_USER={secret.ZAKU_USER};
      export ZAKU_URI=http://escher.csail.mit.edu:8100;
      export WEAVER_DATA_SERVER=http://escher.csail.mit.edu:4000;
      export ML_LOGGER_ROOT=http://escher.csail.mit.edu:4000;
      export MUJOCO_GL=egl;
      export CPATH=$CONDA_PREFIX/include;
      export LUCIDXR_CACHE={secret.JYNS_SLURM_DIR}/.cache;
      export LUCIDSIM_EVAL_DATASETS=/data/scratch/geyang/lucidxr/eval_datasets;
    pypath: "{mounts[0].host_path}:{mounts[1].host_path}"
    work_dir: "{mounts[0].host_path}"
    # partition: normal # not clear what the partition is like
    time_limit: "1-23:0:0"
    n_cpu: 10
    n_gpu: 1
    mem: 60G
    account: vision-billf
    partition: vision-billf
#    qos: vision-billf-main
    # nodelist: "isola-titanrtx-1,isola-v100-[1-2]"
    # interactive: true
    # post_script: >-
    #   make --directory $HOME cleanup;
  launch: !ENV
    type: ssh
    ip: "{secret.JYNS_SLURM_HOST}"
    username: "{secret.JYNS_USERNAME}"
    password: "{secret.JYNS_SLURM_PASSWORD}"
    launch_dir: "{secret.JYNS_SLURM_DIR}"

modes:
  default:
    <<: *default_runner
  render:
    <<: *default_runner
    runner: !runners.Slurm
      <<: *slurm
      account: vision-phillipi
      partition: vision-shared-rtx3090,vision-shared-rtx4090,vision-shared-a100
      qos: lab-free
      time_limit: "12:0:0"
      n_cpu: 15
      n_gpu: 1
      mem: 60G
  eval:
    <<: *default_runner
    runner: !runners.Slurm
      <<: *slurm
      account: vision-phillipi
      partition: vision-shared-rtx3090,vision-shared-v100
      qos: lab-free
      time_limit: "24:0:0"
      n_cpu: 15
      n_gpu: 1
      mem: 60G
  24_gb:
    <<: *default_runner
    runner: !runners.Slurm
      <<: *slurm
      account: vision-phillipi
      partition: csail-shared
#      qos: lab-free
      exclude: >-
        isola-h200-1, sitzmann-h200-1, agrawal-h200-1, isola-h100-1, agrawal-h100-1, 
        agrawal-a100-1, beery-a100-1, beery-a100-2, freeman-a100-1, sitzmann-a100-1, 
        agrawal-l40s-1, beery-l40s-1, beery-l40s-2, beery-l40s-3, beery-l40s-4, 
        huang-l40s-1, huang-l40s-2, sitzmann-l40s-1, isola-ada6000-1, gpu21-1.drl, 
        gpu21-2.drl, improbablex005, improbablex006, improbablex007, improbablex008, 
        improbablex009, agrawal-v100-1, freeman-v100-1, freeman-v100-2, isola-v100-1, 
        isola-v100-2, oliva-titanv-1, tig-slurm-2, tig-slurm-3, agrawal-2080ti-1, 
        gpu19-1.drl, gpu19-2.drl, inspector-gadget.drl, isola-2080ti-1, isola-2080ti-2, 
        isola-2080ti-3, isola-2080ti-4, isola-3080-1, isola-3080-2, groenig-0, groenig-1, 
        groenig-2, groenig-3, groenig-4, groenig-5, groenig-6
      time_limit: "3:0:0"
      n_cpu: 8
      n_gpu: 1
      mem: 32G
  32_gb:
    <<: *default_runner
    runner: !runners.Slurm
      <<: *slurm
      account: vision-phillipi
      partition: csail-shared
#      qos: lab-free
      exclude: >-
        isola-h200-1, sitzmann-h200-1, agrawal-h200-1, isola-h100-1, agrawal-h100-1, 
        agrawal-a100-1, beery-a100-1, beery-a100-2, freeman-a100-1, sitzmann-a100-1, 
        agrawal-l40s-1, beery-l40s-1, beery-l40s-2, beery-l40s-3, beery-l40s-4, 
        huang-l40s-1, huang-l40s-2, sitzmann-l40s-1, isola-ada6000-1, gpu21-1.drl, 
        gpu21-2.drl, improbablex005, improbablex006, improbablex007, improbablex008, 
        improbablex009, freeman-titanrtx-1, freeman-titanrtx-2, gpu20-1.drl, gpu20-2.drl, 
        gpu20-3.drl, gpu20-4.drl, isola-titanrtx-1, oliva-titanrtx-1, oliva-titanrtx-3, 
        sitzmann-4090-1, improbablex001, improbablex002, improbablex003, improbablex004, 
        oliva-titanv-1, tig-slurm-2, tig-slurm-3, agrawal-2080ti-1, gpu19-1.drl, 
        gpu19-2.drl, inspector-gadget.drl, isola-2080ti-1, isola-2080ti-2, 
        isola-2080ti-3, isola-2080ti-4, isola-3080-1, isola-3080-2, groenig-0, 
        groenig-1, groenig-2, groenig-3, groenig-4, groenig-5, groenig-6
      time_limit: "3:0:0"
      n_cpu: 12
      n_gpu: 1
      mem: 48G
  48_gb:
    <<: *default_runner
    runner: !runners.Slurm
      <<: *slurm
      account: vision-phillipi
      partition: csail-shared
#      qos: lab-free
      exclude: >-
        isola-h200-1, sitzmann-h200-1, agrawal-h200-1, isola-h100-1, agrawal-h100-1, 
        agrawal-a100-1, beery-a100-1, beery-a100-2, freeman-a100-1, sitzmann-a100-1, 
        agrawal-v100-1, freeman-v100-1, freeman-v100-2, isola-v100-1, isola-v100-2, 
        freeman-titanrtx-1, freeman-titanrtx-2, gpu20-1.drl, gpu20-2.drl, gpu20-3.drl, 
        gpu20-4.drl, isola-titanrtx-1, oliva-titanrtx-1, oliva-titanrtx-3, sitzmann-4090-1, 
        improbablex001, improbablex002, improbablex003, improbablex004, oliva-titanv-1, 
        tig-slurm-2, tig-slurm-3, agrawal-2080ti-1, gpu19-1.drl, gpu19-2.drl, 
        inspector-gadget.drl, isola-2080ti-1, isola-2080ti-2, isola-2080ti-3, 
        isola-2080ti-4, isola-3080-1, isola-3080-2, groenig-0, groenig-1, groenig-2, 
        groenig-3, groenig-4, groenig-5, groenig-6
      time_limit: "3:0:0"
      n_cpu: 16
      n_gpu: 1
      mem: 64G
  80Gb:
    <<: *default_runner
    runner: !runners.Slurm
      <<: *slurm
      account: vision-phillipi
      partition: csail-shared
#      qos: lab-free
      exclude: >-
        isola-h200-1, sitzmann-h200-1, agrawal-h200-1, agrawal-l40s-1, beery-l40s-1, 
        beery-l40s-2, beery-l40s-3, beery-l40s-4, huang-l40s-1, huang-l40s-2, 
      time_limit: "3:0:0"
      n_cpu: 30
      n_gpu: 1
      mem: 120G
  train:
    <<: *default_runner
    mounts: # mount configurations Available keys: NOW, UUID,
      - !mounts.SSHCode
        <<: *code_mount
        <<: *code_mount_posterior-sculpting
        excludes: >-
          --exclude='./docs' 
          --exclude='**/assets' 
          --exclude='**/*.obj'
          --exclude='**/*.stl'
          --exclude='**/*.png'
          --exclude='**/*.jpeg'
          --exclude='**/*.mtl'
          --exclude='data' 
          --exclude='dist'
          --exclude='.pytest_cache'
          --exclude='datasets' 
          --exclude='docs' 
          --exclude='specs'
          --exclude='outputs'
          --exclude='figures' 
          --exclude='results' 
          --exclude='analysis' 
          --exclude='*.ipynb'
          --exclude='*__pycache__' 
          --exclude='*.egg-info'
          --exclude='*.git' 
          --exclude='*.gif'
          --exclude='*.mp4' 
          --exclude='*.idea'
          --exclude='*.pkl'
          --exclude='*.log*' 
          --exclude='*.hdf5'
          --exclude='**/orbit'
          --exclude='.cache'
        compress: true
    runner: !runners.Slurm
      <<: *slurm
      account: vision-phillipi
      partition: vision-phillipi
#      partition: csail-shared
#      qos: vision-phillipi-main
#      qos: lab-free
      gres: gpu:h200:1
      time_limit: "12:0:0"
      n_cpu: 16
      n_gpu: 1
      mem: 100G


