version: 0
#verbose: true
run: &default_runner
  mounts: # mount configurations Available keys: NOW, UUID,
    - !mounts.SSHCode &code_mount
      local_path: .
      local_tar: /home/ravan/jaynes/{now:%Y-%m-%d}/{now:%H%M%S.%f}-lucidxr.tar
      host_path: "{secret.45_JYNS_SLURM_DIR}/jaynes_mount/lucidxr/{now:%Y-%m-%d}/{now:%H%M%S.%f}-lucidxr"
      remote_tar: "{secret.45_JYNS_SLURM_DIR}/jaynes_mount/lucidxr/{now:%Y-%m-%d}/{now:%H%M%S.%f}-lucidxr.tar"
      pypath: true
      excludes: >-
        --exclude="**/eval_envs"
        --exclude='./docs'
        --exclude='data' 
        --exclude='dist'
        --exclude='.pytest_cache'
        --exclude='.cache'
        --exclude='datasets' 
        --exclude='docs' 
        --exclude='specs'
        --exclude='outputs'
        --exclude='figures' 
        --exclude='results' 
        --exclude='analysis' 
        --exclude='*.ipynb'
        --exclude='*__pycache__' 
        --exclude='*.egg-info'
        --exclude='*.git' 
        --exclude='*.gif'
        --exclude='*.mp4' 
        --exclude='*.idea'
        --exclude='*.pkl'
        --exclude='*.log*' 
        --exclude='*.hdf5'
        --exclude='**/orbit'
      compress: true
    - !mounts.SSHCode &code_mount_posterior-sculpting
      local_path: ../posterior-sculpting
      local_tar: /home/ravan/jaynes/{now:%Y-%m-%d}/{now:%H%M%S.%f}-posterior-sculpting.tar
      host_path: "{secret.45_JYNS_SLURM_DIR}/jaynes_mount/lucidxr/{now:%Y-%m-%d}/{now:%H%M%S.%f}-posterior-sculpting"
      remote_tar: "{secret.45_JYNS_SLURM_DIR}/jaynes_mount/lucidxr/{now:%Y-%m-%d}/{now:%H%M%S.%f}-posterior-sculpting.tar"
      pypath: true
      excludes: >-
        --exclude='./docs' 
        --exclude='**/assets' 
        --exclude='**/*.obj'
        --exclude='**/*.stl'
        --exclude='**/*.png'
        --exclude='**/*.jpeg'
        --exclude='**/*.mtl'
        --exclude='data' 
        --exclude='dist'
        --exclude='.pytest_cache'
        --exclude='docs' 
        --exclude='specs'
        --exclude='outputs'
        --exclude='figures' 
        --exclude='results' 
        --exclude='analysis' 
        --exclude='*.ipynb'
        --exclude='*__pycache__' 
        --exclude='*.egg-info'
        --exclude='*.git' 
        --exclude='*.gif'
        --exclude='*.mp4' 
        --exclude='*.idea'
        --exclude='*.pkl'
        --exclude='*.log*' 
        --exclude='*.hdf5'
        --exclude=".cache"
      compress: true
  runner: !runners.Slurm &slurm
    envs: >-
      LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8 LANGUAGE=en_US MUJOCO_GL=egl
    shell: "/usr/bin/env bash -l"
    startup: >-
      echo "setting up";
      eval "$(/home/common/sync_conda_env.sh torch311)";
      export CPATH=$CONDA_PREFIX/include;
      export ML_LOGGER_HOST={secret.45_ML_LOGGER_HOST};
      export ML_LOGGER_ROOT=http://escher.csail.mit.edu:4000;
      export ML_LOGGER_USER={secret.45_ML_LOGGER_USER};
      export MUJOCO_GL=egl;
      export ZAKU_URI=http://escher.csail.mit.edu:8100;
      export ZAKU_USER={secret.45_ZAKU_USER};
      export LUCIDXR_CACHE={secret.45_LUCID_CACHE_DIR}/.cache;
      export DATASETS=$LUCIDXR_CACHE;
      export ROBOHIVE_ROOT={secret.45_ROBOHIVE_ROOT};
      export LUCIDSIM_EVAL_DATASETS=/home/ravan/lucidxr/eval_datasets;
    pypath: "{mounts[0].host_path}:{mounts[1].host_path}"
    work_dir: "{mounts[0].host_path}"
    time_limit: "1-23:0:0"
#    n_cpu: 10
#    n_gpu: 1
#    mem: 60G
#    account: vision-billf
    partition: standard
#    qos: vision-billf-main
    # nodelist: "isola-titanrtx-1,isola-v100-[1-2]"
    # interactive: true
    # post_script: >-
    #   make --directory $HOME cleanup;
    exclude: lucid-node-016,lucid-node-002,lucid-node-052
  launch: !ENV
    type: ssh
    ip: "{secret.45_JYNS_SLURM_HOST}"
    username: "{secret.45_JYNS_USERNAME}"
    pem: "{secret.45_JYNS_SLURM_PEM}"
    launch_dir: "{secret.45_JYNS_SLURM_DIR}"

modes:
  default:
    <<: *default_runner
  train:
    <<: *default_runner
    mounts: # mount configurations Available keys: NOW, UUID,
      - !mounts.SSHCode
        <<: *code_mount
        excludes: >- 
          --exclude='./docs' 
          --exclude='**/assets' 
          --exclude='**/*.obj'
          --exclude='**/*.stl'
          --exclude='**/*.png'
          --exclude='**/*.jpeg'
          --exclude='**/*.mtl'
          --exclude='data' 
          --exclude='dist'
          --exclude='.pytest_cache'
          --exclude='datasets' 
          --exclude='docs' 
          --exclude='specs'
          --exclude='outputs'
          --exclude='figures' 
          --exclude='results' 
          --exclude='analysis' 
          --exclude='*.ipynb'
          --exclude='*__pycache__' 
          --exclude='*.egg-info'
          --exclude='*.git' 
          --exclude='*.gif'
          --exclude='*.mp4' 
          --exclude='*.idea'
          --exclude='*.pkl'
          --exclude='*.log*' 
          --exclude='*.hdf5'
          --exclude='**/orbit'
          --exclude='.cache'
      - !mounts.SSHCode
        <<: *code_mount_posterior-sculpting
    runner: !runners.Slurm
      <<: *slurm
#      account: vision-ph\illipi
#      qos: lab-free
#      gres: gpu:1
      time_limit: "24:0:0"
#      n_cpu: 40
      gpus: 0
      mem: 90G
  render:
    <<: *default_runner
    mounts: # mount configurations Available keys: NOW, UUID,
      - !mounts.SSHCode
        <<: *code_mount
      - !mounts.SSHCode
        <<: *code_mount_posterior-sculpting
        excludes: >-
          --exclude='./docs' 
          --exclude='**/eval_envs' 
          --exclude='data' 
          --exclude='dist'
          --exclude='.pytest_cache'
          --exclude='datasets' 
          --exclude='docs' 
          --exclude='specs'
          --exclude='outputs'
          --exclude='figures' 
          --exclude='results' 
          --exclude='analysis' 
          --exclude='*.ipynb'
          --exclude='*__pycache__' 
          --exclude='*.egg-info'
          --exclude='*.git' 
          --exclude='*.gif'
          --exclude='*.mp4' 
          --exclude='*.idea'
          --exclude='*.pkl'
          --exclude='*.log*' 
          --exclude='*.hdf5'
          --exclude="**/orbit" 
          --exclude=".cache"
        compress: true
    runner: !runners.Slurm
      <<: *slurm
      time_limit: "24:0:0"
      gpus: 0
      mem: 90G
