version: 0
#verbose: true
run:
  mounts: # mount configurations Available keys: NOW, UUID,
    - !mounts.SSHCode &code_mount
      local_path: .
      # host_path: $JYNMNT/latent-planning/latent-planning
      local_tar: /tmp/{now:%Y-%m-%d}/{now:%H%M%S.%f}-jaynes-demo.tar
      host_path: "{secret.JYNS_SLURM_DIR}/jaynes-demo/{now:%Y-%m-%d}/{now:%H%M%S.%f}-jaynes_demo"
      remote_tar: "{secret.JYNS_SLURM_DIR}/jaynes-demo/{now:%Y-%m-%d}/{now:%H%M%S.%f}-jaynes_demo.tar"
      pypath: true
#      exclude_ignore: .gitignore
      excludes: >-
        --exclude='./docs' 
        --exclude='./assets' 
        --exclude='data' 
        --exclude='dist'
        --exclude='.pytest_cache'
        --exclude='datasets' 
        --exclude='docs' 
        --exclude='specs'
        --exclude='outputs'
        --exclude='figures' 
        --exclude='results' 
        --exclude='analysis' 
        --exclude='*.ipynb'
        --exclude='*__pycache__' 
        --exclude='*.egg-info'
        --exclude='*.git' 
        --exclude='*.gif'
        --exclude='*.mp4' 
        --exclude='*.idea'
        --exclude='*.pkl'
        --exclude='*.log*' 
        --exclude='*.hdf5'
      compress: true
      
    - !mounts.SSHCode &vuer_envs_real
      local_path: ../vuer-envs-real
      # host_path: $JYNMNT/latent-planning/latent-planning
      local_tar: /tmp/{now:%Y-%m-%d}/{now:%H%M%S.%f}-lucidxr.tar
      host_path: "{secret.JYNS_SLURM_DIR}/lucidxr-real/{now:%Y-%m-%d}/{now:%H%M%S.%f}-lucidxr"
      remote_tar: "{secret.JYNS_SLURM_DIR}/lucidxr-real/{now:%Y-%m-%d}/{now:%H%M%S.%f}-lucidxr.tar"
      pypath: true
      compress: true
      excludes: >-
        --exclude='./assets' 
        --exclude='data' 
        --exclude='dist'
        --exclude='.pytest_cache'
        --exclude='*__pycache__' 
        --exclude='*.egg-info'
        --exclude='*.git' 
        --exclude='*.idea'
        --exclude='*.pkl'
        --exclude='*.log*' 
        --exclude='*.hdf5'

    - !mounts.SSHCode &ur5py
      local_path: ../ur5py
      # host_path: $JYNMNT/latent-planning/latent-planning
      local_tar: /tmp/{now:%Y-%m-%d}/{now:%H%M%S.%f}-ur5py.tar
      host_path: "{secret.JYNS_SLURM_DIR}/ur5py/{now:%Y-%m-%d}/{now:%H%M%S.%f}-ur5py"
      remote_tar: "{secret.JYNS_SLURM_DIR}/ur5py/{now:%Y-%m-%d}/{now:%H%M%S.%f}-ur5py.tar"
      pypath: true
      compress: true

  runner: !runners.Slurm &slurm
    envs: >-
      LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8 LANGUAGE=en_US
      MUJOCO_GL=egl
    setup: |
      source "{secret.JYNS_SLURM_DIR}/.jaynes_init"
      export CONDARC=/dev/null
      export CONDA_NO_RC=1
      conda activate torch311
      export MUJOCO_GL=egl
      export CPATH=$CONDA_PREFIX/include
      export LUCIDXR_CACHE={secret.JYNS_SLURM_DIR}/.cache
    pypath: "{mounts[0].host_path}:{mounts[1].host_path}:{mounts[2].host_path}"
    work_dir: "{mounts[0].host_path}"
    # partition: normal # not clear what the partition is like
    time_limit: "1-23:0:0"
    n_cpu: 10
    n_gpu: 1
    mem: 60G
    account: vision-phillipi
    partition: vision-phillipi
    qos: vision-phillipi-main
    # nodelist: "isola-titanrtx-1,isola-v100-[1-2]"
    # interactive: true
    # post_script: >-
    #   make --directory $HOME cleanup;
launch: !ENV
    type: ssh
    ip: "{secret.JYNS_SLURM_HOST}"
    username: "{secret.JYNS_USERNAME}"
    password: "{secret.JYNS_SLURM_PASSWORD}"
    launch_dir: "{secret.JYNS_SLURM_DIR}/lucidxr"

